version: '3.8'

services:
  frontend:
    build:
      context: .
      dockerfile: ./app/ci/Dockerfile
    restart: unless-stopped
    ports:
      - "443:443"
      - "80:80"
    volumes:
      - /etc/ssl/heroes-might-and-magic:/etc/nginx/ssl:ro
    networks:
      - web

networks:
  web:
    driver: bridge