version: '3.8'

services:
  frontend:
    build:
      context: .
      dockerfile: ./app/ci/Dockerfile
    restart: unless-stopped
    ports:
      - "80:80"
    networks:
      - web

networks:
  web:
    driver: bridge